// src/components/cart/CheckoutDialog.tsx
"use client";

import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useCart } from '@/hooks/use-cart';
import { useToast } from '@/hooks/use-toast';
import { Loader2, CheckCircle2, MapPin } from 'lucide-react';
import { placeOrder } from '@/actions/admin';

interface CheckoutDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function CheckoutDialog({ open, onOpenChange }: CheckoutDialogProps) {
  const { cart, totalPrice, clearCart } = useCart();
  const { toast } = useToast();
  const [isProcessing, setIsProcessing] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const [deliveryAddress, setDeliveryAddress] = useState('');

  const handlePayment = async () => {
    setIsProcessing(true);

    // Save order to Supabase
    const result = await placeOrder({
      items: cart.map((item) => ({
        id: item.id,
        name: item.name,
        price: item.price,
        quantity: item.quantity,
      })),
      totalAmount: totalPrice,
      deliveryAddress: deliveryAddress.trim() || undefined,
    });

    setIsProcessing(false);

    if (!result.success) {
      toast({
        title: 'Order Failed',
        description: result.message ?? 'Something went wrong. Please try again.',
        variant: 'destructive',
      });
      return;
    }

    setIsSuccess(true);
    clearCart();
    setDeliveryAddress('');
    toast({
      title: 'Order Placed!',
      description: 'Your delicious food is on its way. Thank you for your order!',
    });
    setTimeout(() => {
      onOpenChange(false);
      setTimeout(() => setIsSuccess(false), 500);
    }, 3000);
  };

  const handleClose = () => {
    onOpenChange(false);
    if (isSuccess) {
      setTimeout(() => setIsSuccess(false), 500);
    }
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{isSuccess ? 'Payment Successful!' : 'Complete Your Order'}</DialogTitle>
          <DialogDescription>
            {isSuccess
              ? 'Your order has been confirmed and recorded.'
              : 'Review your order details and proceed to payment.'}
          </DialogDescription>
        </DialogHeader>

        {isSuccess ? (
          <div className="flex flex-col items-center justify-center space-y-4 my-8">
            <CheckCircle2 className="h-24 w-24 text-green-500" />
            <p className="text-lg font-medium">Thank you for your purchase!</p>
            <p className="text-muted-foreground text-center text-sm">
              Your order has been saved. This dialog will close automatically.
            </p>
          </div>
        ) : (
          <div className="my-4 space-y-4">
            {/* Order Summary */}
            <div>
              <h3 className="font-semibold mb-2">Order Summary</h3>
              <div className="space-y-2 rounded-md bg-muted p-4">
                {cart.map((item) => (
                  <div key={item.id} className="flex justify-between text-sm">
                    <span>{item.name} × {item.quantity}</span>
                    <span>${(item.price * item.quantity).toFixed(2)}</span>
                  </div>
                ))}
                <div className="border-t border-border mt-3 pt-3" />
                <div className="flex justify-between font-bold">
                  <span>Total</span>
                  <span>${totalPrice.toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* Delivery Address */}
            <div className="space-y-1.5">
              <Label htmlFor="delivery-address" className="flex items-center gap-1.5">
                <MapPin className="h-3.5 w-3.5" />
                Delivery Address <span className="text-muted-foreground font-normal">(optional)</span>
              </Label>
              <Textarea
                id="delivery-address"
                placeholder="Enter your delivery address…"
                value={deliveryAddress}
                onChange={(e) => setDeliveryAddress(e.target.value)}
                rows={2}
                className="resize-none"
              />
            </div>
          </div>
        )}

        {!isSuccess && (
          <DialogFooter>
            <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isProcessing}>
              Cancel
            </Button>
            <Button onClick={handlePayment} disabled={isProcessing || cart.length === 0}>
              {isProcessing ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Processing…
                </>
              ) : (
                `Pay $${totalPrice.toFixed(2)}`
              )}
            </Button>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/components/CheckoutDialog.vue
<template>
  <div v-if="open" class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <!-- Backdrop overlay -->
    <div @click="handleClose" class="fixed inset-0 bg-black/50 backdrop-blur-sm transition-opacity duration-300"></div>

    <!-- Dialog box container -->
    <div class="relative w-full max-w-md rounded-xl bg-background p-6 shadow-2xl z-50 border border-border/50 animate-in fade-in zoom-in-95 duration-200">
      <!-- Header -->
      <div class="mb-4">
        <h2 class="text-xl font-bold text-foreground">
          {{ isSuccess ? 'Payment Successful!' : 'Complete Your Order' }}
        </h2>
        <p class="text-sm text-muted-foreground mt-1">
          {{ isSuccess ? 'Your order has been confirmed and recorded.' : 'Review your order details and proceed to payment.' }}
        </p>
      </div>

      <!-- Success Content -->
      <div v-if="isSuccess" class="flex flex-col items-center justify-center space-y-4 my-8">
        <CheckCircle2 class="h-24 w-24 text-green-500 animate-bounce" />
        <p class="text-lg font-medium text-foreground">Thank you for your purchase!</p>
        <p class="text-muted-foreground text-center text-sm">
          Your order has been saved. This dialog will close automatically.
        </p>
      </div>

      <!-- Checkout Form Content -->
      <div v-else class="my-4 space-y-4">
        <!-- Order Summary -->
        <div>
          <h3 class="font-semibold text-sm mb-2">Order Summary</h3>
          <div class="space-y-2 rounded-md bg-muted p-4 border border-border/30">
            <div 
              v-for="item in cartStore.cart" 
              :key="item.id" 
              class="flex justify-between text-xs text-foreground/80 font-medium"
            >
              <span>{{ item.name }} × {{ item.quantity }}</span>
              <span>${{ (item.price * item.quantity).toFixed(2) }}</span>
            </div>
            <div class="border-t border-border mt-3 pt-3"></div>
            <div class="flex justify-between font-bold text-sm text-foreground">
              <span>Total</span>
              <span class="text-primary">${{ cartStore.totalPrice.toFixed(2) }}</span>
            </div>
          </div>
        </div>

        <!-- Delivery Address -->
        <div class="space-y-1.5">
          <label for="delivery-address" class="flex items-center gap-1.5 text-xs font-semibold text-muted-foreground">
            <MapPin class="h-3.5 w-3.5 text-primary" />
            Delivery Address <span class="font-normal">(optional)</span>
          </label>
          <textarea
            id="delivery-address"
            placeholder="Enter your delivery address…"
            v-model="deliveryAddress"
            rows="2"
            class="w-full rounded-md border border-border bg-card p-2.5 text-sm focus:outline-none focus:ring-1 focus:ring-primary focus:border-primary resize-none placeholder:text-muted-foreground"
          ></textarea>
        </div>

        <!-- Form Action Buttons -->
        <div class="flex justify-end gap-2 pt-2">
          <button 
            @click="handleClose" 
            :disabled="isProcessing"
            class="px-4 py-2 border border-border rounded-md text-sm font-semibold hover:bg-secondary disabled:opacity-50 transition-colors cursor-pointer"
          >
            Cancel
          </button>
          <button 
            @click="handlePayment" 
            :disabled="isProcessing || cartStore.cart.length === 0"
            class="px-5 py-2 bg-primary text-white rounded-md text-sm font-bold hover:bg-primary/95 disabled:opacity-50 flex items-center justify-center transition-colors cursor-pointer shadow-sm"
          >
            <Loader2 v-if="isProcessing" class="mr-2 h-4 w-4 animate-spin" />
            <span>{{ isProcessing ? 'Processing…' : `Pay $${cartStore.totalPrice.toFixed(2)}` }}</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useCartStore } from '../store/cart';
import { useAuthStore } from '../store/auth';
import { Loader2, CheckCircle2, MapPin } from '@lucide/vue';

const props = defineProps<{
  open: boolean;
}>();

const emit = defineEmits(['update:open']);

const cartStore = useCartStore();
const authStore = useAuthStore();

const isProcessing = ref(false);
const isSuccess = ref(false);
const deliveryAddress = ref('');

const handlePayment = async () => {
  isProcessing.value = true;

  try {
    const authHeaders = await authStore.getAuthHeader();
    
    // API server runs on port 5000
    const response = await fetch('http://localhost:5000/api/orders', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...authHeaders
      },
      body: JSON.stringify({
        items: cartStore.cart.map((item) => ({
          id: item.id,
          name: item.name,
          price: item.price,
          quantity: item.quantity,
        })),
        totalAmount: cartStore.totalPrice,
        deliveryAddress: deliveryAddress.value.trim() || undefined,
      }),
    });

    const result = await response.json();

    isProcessing.value = false;

    if (!response.ok) {
      alert(result.error || 'Something went wrong. Please try again.');
      return;
    }

    isSuccess.value = true;
    cartStore.clearCart();
    deliveryAddress.value = '';
    
    // Close automatically after 3 seconds
    setTimeout(() => {
      handleClose();
    }, 3000);
  } catch (err) {
    isProcessing.value = false;
    console.error('Order network error:', err);
    alert('Failed to connect to order server.');
  }
};

const handleClose = () => {
  if (isProcessing.value) return;
  emit('update:open', false);
  // Reset success state after animation transition
  setTimeout(() => {
    isSuccess.value = false;
  }, 300);
};
</script>
