// src/components/cards/HotelCard.tsx
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ChevronRight } from 'lucide-react';
import type { Hotel } from '@/lib/data';

interface HotelCardProps {
  hotel: Hotel;
}

export default function HotelCard({ hotel }: HotelCardProps) {
  const [imgSrc, setImgSrc] = useState(hotel.image_url);

  return (
    <Link href={`/hotel/${hotel.id}`} className="group">
      <Card className="flex flex-col overflow-hidden shadow-sm transition-all duration-300 hover:shadow-xl h-full">
        <CardHeader className="p-0">
          <div className="aspect-video overflow-hidden bg-muted relative">
            <Image
              src={imgSrc || "https://placehold.co/600x400?text=Foodie+Forecast"}
              alt={hotel.name}
              width={600}
              height={400}
              className="object-cover w-full h-full transition-transform duration-300 group-hover:scale-105"
              onError={() => setImgSrc("https://placehold.co/600x400?text=No+Image")}
            />
          </div>
        </CardHeader>
        <CardContent className="p-4 flex-grow flex justify-between items-start">
          <div>
            <CardTitle className="text-xl font-semibold group-hover:text-primary transition-colors">{hotel.name}</CardTitle>
            <CardDescription>{hotel.cuisine}</CardDescription>
          </div>
          <ChevronRight className="h-6 w-6 text-muted-foreground transition-transform duration-300 group-hover:translate-x-1 group-hover:text-primary" />
        </CardContent>
      </Card>
    </Link>
  );
}

// frontend/src/components/HotelCard.vue
<template>
  <router-link :to="`/hotel/${hotel.id}`" class="group">
    <div class="flex flex-col overflow-hidden bg-card border border-border/40 rounded-xl shadow-sm transition-all duration-300 hover:shadow-lg h-full">
      <!-- Thumbnail -->
      <div class="aspect-video overflow-hidden bg-muted relative">
        <img 
          :src="imgSrc || 'https://placehold.co/600x400?text=Foodie+Forecast'" 
          :alt="hotel.name"
          class="object-cover w-full h-full transition-transform duration-300 group-hover:scale-105"
          @error="handleImgError"
        />
      </div>

      <!-- Description content -->
      <div class="p-4 flex-grow flex justify-between items-start">
        <div>
          <h3 class="text-lg font-bold group-hover:text-primary transition-colors text-foreground line-clamp-1">
            {{ hotel.name }}
          </h3>
          <p class="text-sm text-muted-foreground mt-1 line-clamp-2">{{ hotel.cuisine }}</p>
        </div>
        <ChevronRight class="h-6 w-6 shrink-0 text-muted-foreground transition-transform duration-300 group-hover:translate-x-1 group-hover:text-primary mt-1" />
      </div>
    </div>
  </router-link>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { ChevronRight } from 'lucide-vue-next';

interface Hotel {
  id: string;
  name: string;
  cuisine: string;
  image_url: string;
}

const props = defineProps<{
  hotel: Hotel;
}>();

const imgSrc = ref(props.hotel.image_url);

const handleImgError = () => {
  imgSrc.value = 'https://placehold.co/600x400?text=No+Image';
};
</script>
